# Veri Setleri Hakkında Bilgiler

In [4]:
import pickle

pkl_dosya_yolu = "/home/uynk/Belgeler/Analyze_Projects/AliBaba_GenAI_Dataset/dataframes.pkl"

# Dosyayı 'rb' (Read Binary - İkili Okuma) formatında açıp içeriğini yüklüyoruz
with open(pkl_dosya_yolu, 'rb') as dosya:
    dataframes = pickle.load(dosya)

In [6]:
dataframes["basemodel_update_latency_anon.csv"]

      timestamp_anon    value                      container_ip
0       1.662859e+09   2639.0  086b31f81b1cf0f15e43fe568e3fb8e4
1       1.662859e+09   2766.0  47d94ec84e80267e738db2caca3d9184
2       1.662859e+09   2639.0  03dc060838ef05053bdea6d483cde7e5
3       1.662860e+09  39010.0  ff0a53d0bc20c807643d80daf7c71887
4       1.662860e+09   2652.0  3ed83727fd0a4a21f681882036a57972
...              ...      ...                               ...
7526    1.662939e+09   3000.0  0ec705c2842d35b28efbea446e2c9255
7527    1.662939e+09   3068.0  e02e18dca6eef690db7e3911f7c82f70
7528    1.662939e+09   2670.0  6dcc7f244fba016765742bf41e7605e9
7529    1.662939e+09   2712.0  0ec705c2842d35b28efbea446e2c9255
7530    1.662939e+09   2660.0  23b8eba99c14e73d454503a55ae96989

[7531 rows x 3 columns]

### **<span style="color:#8CC0EB"> İstek İzleme Verileri </span>**

In [ ]:
dataframes["qps.csv"].head() #  Üretken istekler ve API istekleri de dahil olmak üzere sistem istek hacminin anonimleştirilmiş örnekleme verileri. 

# timestamp_anon: Olayın saniye saniyesine ne zaman gerçekleştiği.
# value: o spesifik zaman diliminde gelen saniye başına istek sayısıdır. 
# container_ip: İsteği karşılayan pod'un şifrelenmiş halidir.
# request_type: Sisteme gelen yükün sınıfları. API_request yalnızca CPU yu meşgul eden hafif trafiktir gibi.

### **<span style="color:#8CC0EB"> Kuyruk İzleme Verileri (Kuyruk) </span>**

In [7]:
display(dataframes["queue_size_raw_anon.csv"].head()) # Her 1 saniyede veya milisaniyede Messege Queue içerisinde işlem görmeyi bekleyen kaç tane Stable diffusion ya da GenAI isteğinin biriktiğini gösteren veri setidir.
# value: İlgili zaman dilimi ve podda işlenmeyi bekleyen toplam istek sayısı.
# container_ip: Pod'un IP si.
# timestampt_anon: isteğin kuyruğa girdiği ve ölçüldüğü zaman.

dataframes["queue_rt_raw_anon.csv"].head() # Bir isteğin Messega Queue'ya girdiği an ile nihayet bir pod tarafından kabul edilip GPU üzerinden işlenmeye başladığı an arasındaki kuyrukta ne kadar süre harcadığını gösterir. Yani isteklerin kuyurkta geçirdikleri saf bekleme süreleri.
# value: Kurukta bekleme süresi(Wt), sistemin bir isteği(API req) kabul etmesiyle yani pod'a ulaştığında, içerideki python scrip'i o an başka bir isteği işliyor ise. Benim işlem sıram ne zaman gelecek diye beklediği süredir.
# container_ip: Pod'un IP adresi
# timestampt_anon: Ölçümün yapıldığı anonimleştirilmiş zaman noktasıdır.

   value  container_ip  timestamp_anon
0    0.0           NaN    1.662859e+09
1    0.0           NaN    1.662859e+09
2    0.0           NaN    1.662859e+09
3    0.0           NaN    1.662859e+09
4    0.0           NaN    1.662859e+09

   value                      container_ip  timestamp_anon
0  196.0  dfe00e981377fa8e0a9aefbc9b2e9369    1.662859e+09
1  425.0  081177dd05d758b23a62391e75a1bb34    1.662860e+09
2  240.0  31408984596c7411b56cfc43d280bc02    1.662860e+09
3  141.0  3b90a898e6de1e8df928ac6175f92bde    1.662860e+09
4  293.0  d9a22a02d2ceb58ec16737de30e46541    1.662860e+09

### **<span style="color:#8CC0EB"> Model Bileşen Yükleme Gecikmesi (Servis) </span>** 

- **Basemodel:** Eğer bir kullanıc "Bir kedi çiz" veya "gün batımı resmi yap" diyorsa. Sistem hafızasındaki genel kedi ve gün batımı resimlerini kullanır. Eğer bir WarmStart durumu varsa gecikme 0 a yakınıdr. Ancak sistem, ilk kez ayağa kalkıyorsa(ColdStart) gecikme yaşanır. 
- **LoRA:** Basemodel'e eklenen küçük stil yamalarıdır. Eğer kullanıcı, bir kedi çiz ama "Van Gogh tarzında" olsun veya "Witcher" gibi olsun diyorsa LoRA devreye girer.
- **ControlNet:** Eğer kullanıcı "şu duruştaki gibi bir resim yap" diyerek referans görsel/poz veriyorsa gecikme devreye girer.

In [8]:
display(dataframes["basemodel_update_latency_anon.csv"].head()) # Sistemin çalışması için en büyük ve en ağır olan devasa modelin belleğe yüklenmesi süresi. Ya da podlara yüklenmiş olan basemodel'in güncellenmesi süresi. 
# value: Basemodel'in dış dikten(Persistent Volume) okunup GPU'ya yüklenmesinde(güncellenmesinde) geçen süre. 
# container_ip: Model yükleme işleminin gerçekleştiği pod'un IP adresi. 

display(dataframes["lora_update_latency_anon.csv"].head()) # LoRA'lar temel modele göre çok daha küçüktür. Bu dosya, isteğin ihtiyaç duyduğu LoRA "yamasının"(yüz tanıma, stil aktarımı vb.) verisidir.
# timestampt_anon: Gecikmenin ölçüldüğü zaman noktası.
# value: LoRA ağırlıklarının depolama alanlarından(Persistent Volume, Object Storage) okunup, hali hazırda VRAM de duran Basemodel üzerine bindirilmesi için geçen süre. Basemodel değerinden daha düşük olmalıdır.
# container_ip: LoRA yükleme işlenin gerçekleştiği benzersiz container_ip

display(dataframes["controlnet_latency_data_anon.csv"].head()) # ControlNet, üretilen görselin yapısını kontrol etmemizi sağlar. ControlNet genellikle LoRA'dan daha büyük, temel modelden (Base Model) ise daha küçüktür.
# timestampt_anon: ölçümün yapıldığı zaman. 
# value: ControlNet ağırlıklarının depolama alanından(Volume) okunup GPU belleğine (VRAM) yüklenmesi için geçen toplam süre.
# container_ip: benzersiz IP

dataframes["pipeline_update_latency_anon.csv"].head() # Sadece bir parçanın değil; Temel Model + LoRA + ControlNet gibi tüm bileşenlerin bir araya getirilip "çıkarım (inference)" yapmaya hazır hale gelmesi için geçen toplam süredir verisi.
# timestampt_anon: Ölçümün yapıldığı zaman.
# value: Bir isteğin, işlenmeye başlaması için gereken tüm bileşenlerin, yüklenme ve birbirine entegre edilme süresini ifade eder.
# container_ip: benzrsiz IP.

   timestamp_anon    value                      container_ip
0    1.662859e+09   2639.0  086b31f81b1cf0f15e43fe568e3fb8e4
1    1.662859e+09   2766.0  47d94ec84e80267e738db2caca3d9184
2    1.662859e+09   2639.0  03dc060838ef05053bdea6d483cde7e5
3    1.662860e+09  39010.0  ff0a53d0bc20c807643d80daf7c71887
4    1.662860e+09   2652.0  3ed83727fd0a4a21f681882036a57972

   timestamp_anon   value                      container_ip
0    1.662859e+09  7109.0  7c921d2bb994a9d8b5300708a519c46d
1    1.662859e+09  4018.0  58c43bcd9763c4cc785712bb28ba86fc
2    1.662859e+09   826.0  086b31f81b1cf0f15e43fe568e3fb8e4
3    1.662859e+09  5641.0  35bb9f389301b325c443320fe0466a46
4    1.662859e+09  3874.0  35bb9f389301b325c443320fe0466a46

   timestamp_anon    value                      container_ip
0    1.662859e+09   4775.0  7c921d2bb994a9d8b5300708a519c46d
1    1.662859e+09   5515.0  35bb9f389301b325c443320fe0466a46
2    1.662859e+09   3098.0  35bb9f389301b325c443320fe0466a46
3    1.662859e+09  27384.0  cbfb6b40cb1caa54ab6de789bb801645
4    1.662859e+09  14107.0  cbfb6b40cb1caa54ab6de789bb801645

   timestamp_anon    value                      container_ip
0    1.662859e+09  41427.0  b1a4723079b8baf68c9f60c49c51e9a3
1    1.662859e+09  11916.0  7c921d2bb994a9d8b5300708a519c46d
2    1.662859e+09   3427.0  07ff74bdf1b06c02945c40819ec1d38e
3    1.662859e+09      0.0  47d94ec84e80267e738db2caca3d9184
4    1.662859e+09   3484.0  086b31f81b1cf0f15e43fe568e3fb8e4

### **<span style="color:#8CC0EB"> Kaynak kullanımının izlenme verileri </span>**

In [9]:
display(dataframes["pod_memory_util_anon.csv"].head()) # Her bir podun (konteynırın) ne kadar RAM (sistem belleği) tükettiğini gösterir. Sistemin RAM kaynaklarının verimliliğini gösterir. 
# value: Pod, kendisine ayrılan toplam bellek miktarının ne kadarını aktif olarak kullandığını gösterir.
# timestampt_anon: Bellek kullanımın ölçüldüğü zaman.
# container_ip: Ölçümün yapıldığı spesifik pod.

display(dataframes["pod_gpu_duty_cycle_anon.csv"].head()) # GPU'nun belirli bir zaman diliminde yüzde kaç kapasiteyle "aktif olarak çalıştığını" gösterir.
# value: Belirli bir zaman diliminde GPU'nun ne kadar süre ile aktif olarak hesaplama yaptığını %(yüzde) cinsinden ifade eder. (%100 tam kapasite çalışıyor, %0 pod hazır bekliyor.)
# timestampt_anon: anonim zaman.
# container_ip: spesifik pod.

display(dataframes["pod_gpu_memory_used_bytes_anon.csv"].head()) # VRAM (Video RAM) dediğimiz, ekran kartının kendi belleğinin ne kadarının dolu olduğunu byte cinsinden gösterir. 
# timestampt_anon: ölçüm zamanı.
# value: GPU belleğinde o an aktif olarak tutulan veri miktarı.
# container_ip: Spesifik pod.

      value  timestamp_anon                      container_ip
0  0.662335    1.662859e+09  25da09a77268ccc99a7968b3e453b8f0
1  0.356734    1.662859e+09  ccfa8e249adb8794109c9c63628a2406
2  0.870187    1.662859e+09  f454d558b9ee961a3f617cfd5aa202eb
3  0.852650    1.662859e+09  b1a4723079b8baf68c9f60c49c51e9a3
4  0.834642    1.662859e+09  3fa8c0fcbd73508ae6cf1c521d80c208

   value  timestamp_anon                      container_ip
0    0.0    1.662859e+09  23b8eba99c14e73d454503a55ae96989
1    0.0    1.662859e+09  11415d99a127e215d2148a1f6600007f
2    0.0    1.662859e+09  ae3389e2979abd8ba8c1eeb9868697e0
3    0.0    1.662859e+09  7ded678c006c99a1018de19c833c7ab4
4    0.0    1.662859e+09  4679f355d4cb3ce3f577d45b87911032

   timestamp_anon         value                      container_ip
0    1.662859e+09  3.387949e+10  23b8eba99c14e73d454503a55ae96989
1    1.662859e+09  2.349780e+10  81202f3feffc31e32dbfcb7c74b72b61
2    1.662859e+09  3.348732e+10  3de9cc1314ba06b9d4c8d66a3d361666
3    1.662859e+09  2.627024e+10  41f81ea9810a29e8ba32801ef7d30271
4    1.662859e+09  2.601334e+10  0967ff61bfabc7475c2cac1bc3159c77

### **<span style="color:#8CC0EB"> Çıkarım Performans Verileri (Çıkış) </span>**

In [10]:
display(dataframes["model_predict_data_anon.csv"].head()) # Yükleme süresi hariç, saf model çıkarım süresi. Model GPU belleğine çoktan yüklenmiş, tüm ağırlıklar hazır ve sadece matematiksel hesaplama (matris çarpımları) yapılıyor.
# timerstampt_anon: ölçüm zamanı
# value: Generative req GPU'da fiilen işlendiği süredir. 
# container_ip: Spesifik pod.

dataframes["pipeline_inference_data_anon.csv"].head() # Model yükleme ve çıkarım dahil olmak üzere, çıkarım işlem hattının tam yanıt süresi. İsteğin pod'a girdiği an ile model çıktısı sürecini kapsar. (end-to-end)
# timestamp_anon: işlemin gerçekleştiği zaman dilimi.
# value: İsteğin Pod'a kabul edilmesinden itibaren geçen toplam yanıt süresi.
# container_ip: Spesifik pod.

   timestamp_anon    value                      container_ip
0    1.662859e+09  14752.0  07ff74bdf1b06c02945c40819ec1d38e
1    1.662859e+09  12773.5  0b6beb4d383cbd13d128b205a7b09313
2    1.662859e+09  71687.0  086b31f81b1cf0f15e43fe568e3fb8e4
3    1.662859e+09  69216.0  47d94ec84e80267e738db2caca3d9184
4    1.662859e+09  10907.5  0b6beb4d383cbd13d128b205a7b09313

   timestamp_anon    value                      container_ip
0    1.662859e+09  19106.0  63beb1b84354963cd40aa5fbdac96110
1    1.662859e+09  17536.0  fd0116f494569215a44314670a86eeb3
2    1.662859e+09   8722.0  07ff74bdf1b06c02945c40819ec1d38e
3    1.662859e+09  68392.0  47d94ec84e80267e738db2caca3d9184
4    1.662859e+09   8434.0  0b6beb4d383cbd13d128b205a7b09313

### **<span style="color:#8CC0EB"> İstek Düzeyinde Performans Verileri </span>**

In [11]:
dataframes["lora_request_trace.csv"].head() # Yürütme süresi, komut istemi karmaşıklığı ve model yapılandırması dahil olmak üzere ayrıntılı çıkarım isteği performans özellikleri.
                                            # Her bir tekil LoRA isteğinin seceresini tutan bir olay günlüğüdür. Her API çağrısı bu veriye yeni bir satır olarak yazılır. Bulut sistemine giren müşterilerin tek tek fişleridir.
                                            # qps verisi ile en büyük farkı API istekleri devasa bir kümedir. LoRA istekleri ise bu kümenin sadece bir parçasıdır. 

# gmt_create: isteğin sisteme ulaştığı tam tarih ve saattir. 
# exec_time_seconds: isteğin sistemde geçirdiği toplam süre gün ve saniye türlerinden
# predict_type: İşlemin türü(TXT_2_IMG) sıfırdan metin ile görsel üretme. Ya da (IMG_2_IMG) görselden görsel oluşturma. 
# predict_status: İşlemin durumu
# groupId: kullanıcının veya organizasyonun ananimleştirilmiş kimliği.
# promt_length: metin uzunluğu
# negative_prompt_length: Kötü anatomi.
# num_images_per_prompt: Kaç farklı resim istendiği.
# num_inference_steps: Gürültü temizleme adım sayısıdır.
# checkpoint_model_version_id: İsteğin hangi ana modeli çalıştıracağını belirtir.
# num_lora: Bu isteğe kaç adet özel LoRA yaması ekleneceğini belirtir.

,gmt_create,predict_type,predict_status,exec_time_seconds,groupId,prompt_length,negative_prompt_length,num_images_per_prompt,num_inference_steps,checkpoint_model_version_id,num_lora
0,2024-11-15 16:57:50,TXT_2_IMG,SUCCEED,32.0,G0000,63.0,26.0,1.0,30.0,M0000,0
1,2024-11-15 18:16:14,TXT_2_IMG,SUCCEED,43.0,G0001,93.0,NaN,1.0,40.0,M0001,0
2,2024-11-15 18:17:06,TXT_2_IMG,SUCCEED,36.0,G0001,93.0,NaN,8.0,40.0,M0001,0
3,2024-11-15 18:17:16,IMG_2_IMG,SUCCEED,53.0,G0001,93.0,NaN,8.0,40.0,M0001,0
4,2024-11-15 18:21:34,IMG_2_IMG,SUCCEED,51.0,G0001,79.0,NaN,8.0,40.0,M0001,0

In [12]:
dataframes["data_trace_processed.csv"].head()

,predict_type,exec_time_seconds,style_type,prompt_length,negative_prompt_length,num_images_per_prompt,num_inference_steps,checkpoint_model_version_id,lora_args
0,e867a9754d73155e90d62f88dbedfc62,22.0,88585aaa7d5402c0928a0c8639c83bab,54.0,26.0,1.0,30.0,0a80ffe64c68aa574e80e6c9b9f5308a,[]
1,e867a9754d73155e90d62f88dbedfc62,18.0,NaN,54.0,50.0,1.0,30.0,f9c95dd7e904711eef0f713598886b04,[]
2,e867a9754d73155e90d62f88dbedfc62,28.0,NaN,14.0,NaN,1.0,30.0,f9c4915ff864089286f00a0da73721b7,[{'modelVersionId': '799974951f19a0c730acda238...
3,e867a9754d73155e90d62f88dbedfc62,21.0,NaN,61.0,50.0,1.0,30.0,5ea2fb33fc16c8e4cbbb2aa91f6900dd,[]
4,e867a9754d73155e90d62f88dbedfc62,18.0,NaN,61.0,50.0,1.0,30.0,5ea2fb33fc16c8e4cbbb2aa91f6900dd,[]