# Information about Data Sets

In [1]:
import pickle

pkl_file_path = "/home/uynk/Belgeler/Analyze_Projects/AliBaba_GenAI_Dataset/dataframes.pkl"

with open(pkl_file_path, 'rb') as file:
    dataframes = pickle.load(file)

In [2]:
dataframes["basemodel_update_latency_anon.csv"] # Here is an example dataset

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,2639.0,086b31f81b1cf0f15e43fe568e3fb8e4,2022-09-11 01:21:30,2022-09-11 09:21:30
1,1.662859e+09,2766.0,47d94ec84e80267e738db2caca3d9184,2022-09-11 01:23:24,2022-09-11 09:23:24
2,1.662859e+09,2639.0,03dc060838ef05053bdea6d483cde7e5,2022-09-11 01:24:21,2022-09-11 09:24:21
3,1.662860e+09,39010.0,ff0a53d0bc20c807643d80daf7c71887,2022-09-11 01:25:18,2022-09-11 09:25:18
4,1.662860e+09,2652.0,3ed83727fd0a4a21f681882036a57972,2022-09-11 01:25:18,2022-09-11 09:25:18
...,...,...,...,...,...
7526,1.662939e+09,3000.0,0ec705c2842d35b28efbea446e2c9255,2022-09-11 23:27:42,2022-09-12 07:27:42
7527,1.662939e+09,3068.0,e02e18dca6eef690db7e3911f7c82f70,2022-09-11 23:29:36,2022-09-12 07:29:36
7528,1.662939e+09,2670.0,6dcc7f244fba016765742bf41e7605e9,2022-09-11 23:32:27,2022-09-12 07:32:27
7529,1.662939e+09,2712.0,0ec705c2842d35b28efbea446e2c9255,2022-09-11 23:33:24,2022-09-12 07:33:24
7530,1.662939e+09,2660.0,23b8eba99c14e73d454503a55ae96989,2022-09-11 23:33:24,2022-09-12 07:33:24

### **<span style="color:#8CC0EB"> Request Monitoring Data </span>**

In [3]:
dataframes["qps.csv"].head() # Anonymized sampling data of system request volume, including generative requests and API requests. 

# timestamp_anon: The exact second the event occurred.
# value: The number of requests per second arriving in that specific time window. 
# container_ip: The encrypted version of the pod serving the request.
# request_type: The classes of load coming into the system. E.g., API_request is light traffic that only occupies the CPU.

,timestamp_anon,value,container_ip,request_type,real_time,real_time_CST
0,1.662859e+09,0.09,NaN,API Requests,2022-09-11 01:19:36,2022-09-11 09:19:36
1,1.662859e+09,0.09,NaN,API Requests,2022-09-11 01:20:33,2022-09-11 09:20:33
2,1.662859e+09,0.09,dfe00e981377fa8e0a9aefbc9b2e9369,Generative Requests,2022-09-11 01:23:24,2022-09-11 09:23:24
3,1.662859e+09,0.09,cbfb6b40cb1caa54ab6de789bb801645,Generative Requests,2022-09-11 01:24:21,2022-09-11 09:24:21
4,1.662859e+09,0.09,NaN,API Requests,2022-09-11 01:24:21,2022-09-11 09:24:21

### **<span style="color:#8CC0EB"> Queue Monitoring Data (Queue) </span>**

In [4]:
display(dataframes["queue_size_raw_anon.csv"].head()) # A dataset showing how many Stable Diffusion or GenAI requests are accumulated waiting to be processed in the Message Queue every 1 second or millisecond.
# value: The total number of requests waiting to be processed in the respective time window and pod.
# container_ip: The IP of the pod.
# timestamp_anon: The time the request entered the queue and was measured.

dataframes["queue_rt_raw_anon.csv"].head() # Shows how much time a request spends in the queue between the moment it enters the Message Queue and the moment it is finally accepted by a pod and starts being processed on the GPU. In other words, the pure waiting time of requests in the queue.
# value: Queue waiting time (Wt); when the system accepts a request (API req) and it reaches the pod, if the python script inside is currently processing another request, this is the time it waits for its turn.
# container_ip: IP address of the pod.
# timestamp_anon: The anonymized point in time when the measurement was taken.

   value  container_ip  timestamp_anon           real_time       real_time_CST
0    0.0           NaN    1.662859e+09 2022-09-11 01:12:00 2022-09-11 09:12:00
1    0.0           NaN    1.662859e+09 2022-09-11 01:12:57 2022-09-11 09:12:57
2    0.0           NaN    1.662859e+09 2022-09-11 01:13:54 2022-09-11 09:13:54
3    0.0           NaN    1.662859e+09 2022-09-11 01:14:51 2022-09-11 09:14:51
4    0.0           NaN    1.662859e+09 2022-09-11 01:15:48 2022-09-11 09:15:48

,value,container_ip,timestamp_anon,real_time,real_time_CST
0,196.0,dfe00e981377fa8e0a9aefbc9b2e9369,1.662859e+09,2022-09-11 01:22:27,2022-09-11 09:22:27
1,425.0,081177dd05d758b23a62391e75a1bb34,1.662860e+09,2022-09-11 01:30:03,2022-09-11 09:30:03
2,240.0,31408984596c7411b56cfc43d280bc02,1.662860e+09,2022-09-11 01:32:54,2022-09-11 09:32:54
3,141.0,3b90a898e6de1e8df928ac6175f92bde,1.662860e+09,2022-09-11 01:39:33,2022-09-11 09:39:33
4,293.0,d9a22a02d2ceb58ec16737de30e46541,1.662860e+09,2022-09-11 01:40:30,2022-09-11 09:40:30

### **<span style="color:#8CC0EB"> Model Component Loading Latency (Service) </span>**

- **Basemodel:** If a user says "Draw a cat" or "make a sunset picture", the system uses the general cat and sunset images in its memory. If there is a WarmStart situation, the latency is close to 0. However, if the system is booting up for the first time (ColdStart), latency occurs.
- **LoRA:** These are small style patches added to the Basemodel. If the user says draw a cat but "in the style of Van Gogh" or "like the Witcher", LoRA comes into play.
- **ControlNet:** If the user provides a reference image/pose saying "make a picture with this posture", this latency comes into play.

In [5]:
display(dataframes["basemodel_update_latency_anon.csv"].head()) # The time it takes to load the massive, heaviest model into memory for the system to run. Or the time it takes to update the basemodel loaded into the pods. 
# value: The time spent reading the Basemodel from external storage (Persistent Volume) and loading (updating) it to the GPU. 
# container_ip: The IP address of the pod where the model loading operation takes place. 

display(dataframes["lora_update_latency_anon.csv"].head()) # LoRAs are much smaller than the base model. This file contains the data of the LoRA "patch" (face recognition, style transfer, etc.) needed by the request.
# timestamp_anon: The point in time the latency was measured.
# value: The time it takes to read LoRA weights from storage areas (Persistent Volume, Object Storage) and overlay them onto the Basemodel already residing in VRAM. It should be lower than the Basemodel value.
# container_ip: The unique container_ip where the LoRA loading operation took place.

display(dataframes["controlnet_latency_data_anon.csv"].head()) # ControlNet allows us to control the structure of the generated image. ControlNet is generally larger than LoRA but smaller than the Base Model.
# timestamp_anon: The time the measurement was made. 
# value: The total time it takes to read ControlNet weights from the storage area (Volume) and load them into GPU memory (VRAM).
# container_ip: Unique IP.

dataframes["pipeline_update_latency_anon.csv"].head() # The data for the total time it takes for all components like Base Model + LoRA + ControlNet to be combined and ready to perform "inference", not just a single part.
# timestamp_anon: The time the measurement was made.
# value: Represents the loading and integration time of all components required for a request to start being processed.
# container_ip: Unique IP.

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,2639.0,086b31f81b1cf0f15e43fe568e3fb8e4,2022-09-11 01:21:30,2022-09-11 09:21:30
1,1.662859e+09,2766.0,47d94ec84e80267e738db2caca3d9184,2022-09-11 01:23:24,2022-09-11 09:23:24
2,1.662859e+09,2639.0,03dc060838ef05053bdea6d483cde7e5,2022-09-11 01:24:21,2022-09-11 09:24:21
3,1.662860e+09,39010.0,ff0a53d0bc20c807643d80daf7c71887,2022-09-11 01:25:18,2022-09-11 09:25:18
4,1.662860e+09,2652.0,3ed83727fd0a4a21f681882036a57972,2022-09-11 01:25:18,2022-09-11 09:25:18

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,7109.0,7c921d2bb994a9d8b5300708a519c46d,2022-09-11 01:19:36,2022-09-11 09:19:36
1,1.662859e+09,4018.0,58c43bcd9763c4cc785712bb28ba86fc,2022-09-11 01:21:30,2022-09-11 09:21:30
2,1.662859e+09,826.0,086b31f81b1cf0f15e43fe568e3fb8e4,2022-09-11 01:21:30,2022-09-11 09:21:30
3,1.662859e+09,5641.0,35bb9f389301b325c443320fe0466a46,2022-09-11 01:22:27,2022-09-11 09:22:27
4,1.662859e+09,3874.0,35bb9f389301b325c443320fe0466a46,2022-09-11 01:23:24,2022-09-11 09:23:24

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,4775.0,7c921d2bb994a9d8b5300708a519c46d,2022-09-11 01:19:36,2022-09-11 09:19:36
1,1.662859e+09,5515.0,35bb9f389301b325c443320fe0466a46,2022-09-11 01:22:27,2022-09-11 09:22:27
2,1.662859e+09,3098.0,35bb9f389301b325c443320fe0466a46,2022-09-11 01:23:24,2022-09-11 09:23:24
3,1.662859e+09,27384.0,cbfb6b40cb1caa54ab6de789bb801645,2022-09-11 01:23:24,2022-09-11 09:23:24
4,1.662859e+09,14107.0,cbfb6b40cb1caa54ab6de789bb801645,2022-09-11 01:24:21,2022-09-11 09:24:21

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,41427.0,b1a4723079b8baf68c9f60c49c51e9a3,2022-09-11 01:12:57,2022-09-11 09:12:57
1,1.662859e+09,11916.0,7c921d2bb994a9d8b5300708a519c46d,2022-09-11 01:19:36,2022-09-11 09:19:36
2,1.662859e+09,3427.0,07ff74bdf1b06c02945c40819ec1d38e,2022-09-11 01:21:30,2022-09-11 09:21:30
3,1.662859e+09,0.0,47d94ec84e80267e738db2caca3d9184,2022-09-11 01:21:30,2022-09-11 09:21:30
4,1.662859e+09,3484.0,086b31f81b1cf0f15e43fe568e3fb8e4,2022-09-11 01:21:30,2022-09-11 09:21:30

 ### **<span style="color:#8CC0EB"> Resource utilization monitoring data </span>**

In [6]:
display(dataframes["pod_memory_util_anon.csv"].head()) # Shows how much RAM (system memory) each pod (container) consumes. It indicates the efficiency of the system's RAM resources. 
# value: Shows how much of the total allocated memory the pod is actively using.
# timestamp_anon: The time memory usage was measured.
# container_ip: The specific pod where the measurement was taken.

display(dataframes["pod_gpu_duty_cycle_anon.csv"].head()) # Shows at what percentage of capacity the GPU is "actively working" in a given time frame.
# value: Expresses in % (percentage) how long the GPU is actively performing calculations in a specific time frame. (100% running at full capacity, 0% pod standing by.)
# timestamp_anon: Anonymized time.
# container_ip: The specific pod.

display(dataframes["pod_gpu_memory_used_bytes_anon.csv"].head()) # Shows how much of the graphics card's own memory, which we call VRAM (Video RAM), is full in bytes. 
# timestamp_anon: Measurement time.
# value: The amount of data currently actively held in GPU memory.
# container_ip: The specific pod.

,value,timestamp_anon,container_ip,real_time,real_time_CST
0,0.662335,1.662859e+09,25da09a77268ccc99a7968b3e453b8f0,2022-09-11 01:12:00,2022-09-11 09:12:00
1,0.131593,1.662859e+09,60ca0f4914228db4ffe28058506cd240,2022-09-11 01:12:00,2022-09-11 09:12:00
2,0.107173,1.662859e+09,fa0717327354a06b4ceeef6d7f249160,2022-09-11 01:12:00,2022-09-11 09:12:00
3,0.032948,1.662859e+09,9cd20d9c3dcebaf54796126cf30daf5e,2022-09-11 01:12:00,2022-09-11 09:12:00
4,0.707200,1.662859e+09,df3235eae04c7621c688ab5ee3ccf8de,2022-09-11 01:12:00,2022-09-11 09:12:00

,value,timestamp_anon,container_ip,real_time,real_time_CST
0,0.0,1.662859e+09,23b8eba99c14e73d454503a55ae96989,2022-09-11 01:12:00,2022-09-11 09:12:00
1,0.0,1.662859e+09,87b9247bea9e01502012cc8d42e9c7b5,2022-09-11 01:12:00,2022-09-11 09:12:00
2,0.0,1.662859e+09,33bb3250acf588bc98aa04b84527552e,2022-09-11 01:12:00,2022-09-11 09:12:00
3,0.0,1.662859e+09,ae4a8bfb2bc417cc15578aea9d4027c1,2022-09-11 01:12:00,2022-09-11 09:12:00
4,0.0,1.662859e+09,25da09a77268ccc99a7968b3e453b8f0,2022-09-11 01:12:00,2022-09-11 09:12:00

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,3.387949e+10,23b8eba99c14e73d454503a55ae96989,2022-09-11 01:12:00,2022-09-11 09:12:00
1,1.662859e+09,2.375995e+10,6aa82f708c1321cd86dacb1289082ae0,2022-09-11 01:12:00,2022-09-11 09:12:00
2,1.662859e+09,2.600914e+10,35e82ff20955837d507171422a46cbab,2022-09-11 01:12:00,2022-09-11 09:12:00
3,1.662859e+09,2.395393e+10,0e1fe71a611f28739fe7fc6915583da0,2022-09-11 01:12:00,2022-09-11 09:12:00
4,1.662859e+09,2.612239e+10,d9a22a02d2ceb58ec16737de30e46541,2022-09-11 01:12:00,2022-09-11 09:12:00

 ### **<span style="color:#8CC0EB"> Inference Performance Data (Output) </span>**

In [7]:
display(dataframes["model_predict_data_anon.csv"].head()) # Pure model inference time, excluding loading time. The model is already loaded into GPU memory, all weights are ready, and only mathematical computation (matrix multiplications) is being done.
# timestamp_anon: Measurement time.
# value: The time the Generative req is actually processed on the GPU. 
# container_ip: The specific pod.

dataframes["pipeline_inference_data_anon.csv"].head() # The full response time of the inference pipeline, including model loading and inference. Covers the process from the moment the request enters the pod to the model output. (end-to-end)
# timestamp_anon: The time frame when the operation occurred.
# value: The total response time from the moment the request is accepted by the Pod.
# container_ip: The specific pod.

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,14752.0,07ff74bdf1b06c02945c40819ec1d38e,2022-09-11 01:21:30,2022-09-11 09:21:30
1,1.662859e+09,12773.5,0b6beb4d383cbd13d128b205a7b09313,2022-09-11 01:22:27,2022-09-11 09:22:27
2,1.662859e+09,71687.0,086b31f81b1cf0f15e43fe568e3fb8e4,2022-09-11 01:22:27,2022-09-11 09:22:27
3,1.662859e+09,69216.0,47d94ec84e80267e738db2caca3d9184,2022-09-11 01:22:27,2022-09-11 09:22:27
4,1.662859e+09,10907.5,0b6beb4d383cbd13d128b205a7b09313,2022-09-11 01:23:24,2022-09-11 09:23:24

,timestamp_anon,value,container_ip,real_time,real_time_CST
0,1.662859e+09,19106.0,63beb1b84354963cd40aa5fbdac96110,2022-09-11 01:12:00,2022-09-11 09:12:00
1,1.662859e+09,17536.0,fd0116f494569215a44314670a86eeb3,2022-09-11 01:20:33,2022-09-11 09:20:33
2,1.662859e+09,8722.0,07ff74bdf1b06c02945c40819ec1d38e,2022-09-11 01:21:30,2022-09-11 09:21:30
3,1.662859e+09,68392.0,47d94ec84e80267e738db2caca3d9184,2022-09-11 01:22:27,2022-09-11 09:22:27
4,1.662859e+09,8434.0,0b6beb4d383cbd13d128b205a7b09313,2022-09-11 01:22:27,2022-09-11 09:22:27

### **<span style="color:#8CC0EB"> Request-Level Performance Data </span>**

In [8]:
dataframes["lora_request_trace.csv"].head() # Detailed inference request performance metrics, including execution time, prompt complexity, and model configuration.

# gmt_create: The exact date and time the request reached the system. 
# exec_time_seconds: The total time the request spent in the system, in days and seconds.
# predict_type: The type of operation, (TXT_2_IMG) generating images from text from scratch, or (IMG_2_IMG) image-to-image generation. 
# predict_status: Status of the operation.
# groupId: Anonymized ID of the user or organization.
# prompt_length: Length of the text.
# negative_prompt_length: E.g., bad anatomy.
# num_images_per_prompt: How many different images are requested.
# num_inference_steps: Number of denoising steps.
# checkpoint_model_version_id: Specifies which base model the request will run.
# num_lora: Specifies how many custom LoRA patches will be added to this request.

,gmt_create,predict_type,predict_status,exec_time_seconds,groupId,prompt_length,negative_prompt_length,num_images_per_prompt,num_inference_steps,checkpoint_model_version_id,num_lora
0,2024-11-15 16:57:50,TXT_2_IMG,SUCCEED,32.0,G0000,63.0,26.0,1.0,30.0,M0000,0
1,2024-11-15 18:16:14,TXT_2_IMG,SUCCEED,43.0,G0001,93.0,NaN,1.0,40.0,M0001,0
2,2024-11-15 18:17:06,TXT_2_IMG,SUCCEED,36.0,G0001,93.0,NaN,8.0,40.0,M0001,0
3,2024-11-15 18:17:16,IMG_2_IMG,SUCCEED,53.0,G0001,93.0,NaN,8.0,40.0,M0001,0
4,2024-11-15 18:21:34,IMG_2_IMG,SUCCEED,51.0,G0001,79.0,NaN,8.0,40.0,M0001,0

In [9]:
dataframes["data_trace_processed.csv"].head()

,predict_type,exec_time_seconds,style_type,prompt_length,negative_prompt_length,num_images_per_prompt,num_inference_steps,checkpoint_model_version_id,lora_args
0,e867a9754d73155e90d62f88dbedfc62,22.0,88585aaa7d5402c0928a0c8639c83bab,54.0,26.0,1.0,30.0,0a80ffe64c68aa574e80e6c9b9f5308a,[]
1,e867a9754d73155e90d62f88dbedfc62,18.0,NaN,54.0,50.0,1.0,30.0,f9c95dd7e904711eef0f713598886b04,[]
2,e867a9754d73155e90d62f88dbedfc62,28.0,NaN,14.0,NaN,1.0,30.0,f9c4915ff864089286f00a0da73721b7,[{'modelVersionId': '799974951f19a0c730acda238...
3,e867a9754d73155e90d62f88dbedfc62,21.0,NaN,61.0,50.0,1.0,30.0,5ea2fb33fc16c8e4cbbb2aa91f6900dd,[]
4,e867a9754d73155e90d62f88dbedfc62,18.0,NaN,61.0,50.0,1.0,30.0,5ea2fb33fc16c8e4cbbb2aa91f6900dd,[]